/**
 * GET /api/report/:id
 * Download a generated PDF report
 */

import { Env, ErrorResponse } from '../../../src/types';

export const onRequestGet: PagesFunction<Env> = async (context) => {
  const { params, request, env } = context;
  const reportId = params.id as string;

  try {
    // Check authorization
    const authHeader = request.headers.get('Authorization');
    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      return unauthorizedResponse('Missing authorization token');
    }

    const token = authHeader.split(' ')[1];

    // Verify session token
    const sessionData = await env.CACHE.get(`session:${token}`);
    if (!sessionData) {
      return unauthorizedResponse('Invalid or expired session');
    }

    const session = JSON.parse(sessionData);

    // Verify report belongs to this session
    if (session.reportId !== reportId) {
      return forbiddenResponse('Access denied to this report');
    }

    // Fetch report from database
    const report = await env.DB.prepare(`
      SELECT * FROM reports WHERE id = ?
    `).bind(reportId).first();

    if (!report) {
      return notFoundResponse('Report not found');
    }

    // Check if PDF exists in R2
    const pdfKey = `reports/${reportId}.pdf`;
    const pdfObject = await env.STORAGE.get(pdfKey);

    if (pdfObject) {
      // Return existing PDF
      return new Response(pdfObject.body, {
        headers: {
          'Content-Type': 'application/pdf',
          'Content-Disposition': `attachment; filename="realm-of-patterns-${reportId.slice(0, 8)}.pdf"`,
          'Cache-Control': 'private, max-age=3600',
        },
      });
    }

    // PDF doesn't exist yet - generate it
    // (In production, this would be handled by the webhook, but fallback here)
    const pdfBuffer = await generatePDF(env, report);

    // Store in R2
    await env.STORAGE.put(pdfKey, pdfBuffer, {
      httpMetadata: { contentType: 'application/pdf' },
    });

    return new Response(pdfBuffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="realm-of-patterns-${reportId.slice(0, 8)}.pdf"`,
      },
    });
  } catch (error) {
    console.error('Report download error:', error);
    const errorResponse: ErrorResponse = {
      success: false,
      error: {
        code: 'INTERNAL_ERROR',
        message: 'Failed to retrieve report.',
      },
    };
    return new Response(JSON.stringify(errorResponse), {
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    });
  }
};

// ============================================
// PDF Generation (Simplified - use jsPDF in production)
// ============================================

async function generatePDF(env: Env, report: Record<string, unknown>): Promise<ArrayBuffer> {
  const vector8d = JSON.parse(report.vector_8d as string);
  const matches = JSON.parse(report.historical_matches as string);

  // Use Workers AI to generate personalized content
  const insights = await generateInsights(env, vector8d, matches);

  // For now, return a placeholder
  // In production, use jsPDF or a PDF generation service
  const pdfContent = `
THE REALM OF PATTERNS
====================

Your 16D Identity Report
------------------------

Vector: ${vector8d.map((v: number) => v.toFixed(2)).join(', ')}

${insights}

Historical Resonance:
${matches.slice(0, 5).map((m: { name: string; resonance: number }) =>
    `- ${m.name} (${(m.resonance * 100).toFixed(0)}% resonance)`
  ).join('\n')}

---
Generated by The Realm of Patterns
https://therealmofpatterns.pages.dev
`;

  // Convert to ArrayBuffer (in production, use actual PDF generation)
  const encoder = new TextEncoder();
  const bytes = encoder.encode(pdfContent);
  const out = new Uint8Array(bytes.byteLength);
  out.set(bytes);
  return out.buffer;
}

async function generateInsights(
  env: Env,
  vector: number[],
  _matches: { name: string; resonance: number; quote: string }[]
): Promise<string> {
  try {
    const prompt = `You are a cosmic identity guide. Based on this 8D identity vector: [${vector.map(v => v.toFixed(2)).join(', ')}],
    where dimensions are P (Phase/Identity), E (Existence/Structure), μ (Cognition), V (Value/Beauty),
    N (Expansion), Δ (Action), R (Relation), Φ (Field/Witness).

    The highest value indicates the dominant dimension. Write a 2-paragraph personalized insight about this person's
    cosmic signature and their potential for growth. Be specific and meaningful. Do not use generic language.`;

    const result = await env.AI.run('@cf/meta/llama-3.1-8b-instruct' as any, {
      prompt,
      max_tokens: 500,
    });

    return (result as { response: string }).response || 'Your unique cosmic pattern reveals profound potential...';
  } catch (error) {
    console.error('AI insight generation failed:', error);
    return 'Your unique cosmic pattern reveals profound potential for growth and self-discovery.';
  }
}

// ============================================
// Error Responses
// ============================================

function unauthorizedResponse(message: string): Response {
  const error: ErrorResponse = {
    success: false,
    error: { code: 'UNAUTHORIZED', message },
  };
  return new Response(JSON.stringify(error), {
    status: 401,
    headers: { 'Content-Type': 'application/json' },
  });
}

function forbiddenResponse(message: string): Response {
  const error: ErrorResponse = {
    success: false,
    error: { code: 'FORBIDDEN', message },
  };
  return new Response(JSON.stringify(error), {
    status: 403,
    headers: { 'Content-Type': 'application/json' },
  });
}

function notFoundResponse(message: string): Response {
  const error: ErrorResponse = {
    success: false,
    error: { code: 'NOT_FOUND', message },
  };
  return new Response(JSON.stringify(error), {
    status: 404,
    headers: { 'Content-Type': 'application/json' },
  });
}
